import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {invoke} from "@tauri-apps/api/core";
import "./App.css";
import "./Settings.css";
import "./RemoteAddress.css";
import Settings from "./Settings";
localStorage.removeItem("clientApi");
type Stats={connected:boolean;server_addr:string;uptime:number;total_bytes_in:number;total_bytes_out:number;active_proxies:number;reconnect_count:number};
type Proxy={server_addr:string;server_port:number;name:string;type:string;local_port:number;remote_port:number;bytes_in:number;bytes_out:number;connections:number;last_active:string};
type Request={server_addr:string;server_port:number;id:string;local_port:number;proxy_type:string;status:string;remote_port?:number;request_time:string;reason?:string};
const inTauri="__TAURI_INTERNALS__" in window;const api=async<T,>(baseUrl:string,path:string,method="GET",body?:unknown):Promise<T>=>{if(inTauri)return invoke<T>("api_request",{baseUrl,path,method,body:body??null});const res=await fetch(`${baseUrl}${path}`,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});if(!res.ok)throw new Error(await res.text());return res.json()};
const bytes=(v=0)=>{if(!v)return"0 B";const u=["B","KB","MB","GB","TB"],i=Math.min(Math.floor(Math.log(v)/Math.log(1024)),4);return `${(v/1024**i).toFixed(i?2:0)} ${u[i]}`};
const duration=(n=0)=>{const s=Math.floor(n/1e9),h=Math.floor(s/3600),m=Math.floor(s%3600/60);return h?`${h}h ${m}m`:m?`${m}m ${s%60}s`:`${s}s`};
const endpoint=(raw:string)=>{const value=raw.trim();if(!value.includes("://"))throw new Error("请输入包含协议的完整服务地址");const parsed=new URL(value);const scheme=parsed.protocol.toLowerCase();if(!parsed.hostname)throw new Error("服务端地址格式不正确");if(!["http:","https:","tcp:","tls:"].includes(scheme))throw new Error("服务端地址仅支持 http、https、tcp 或 tls 协议");const defaultPort=scheme==="https:"?443:scheme==="http:"?80:7100;const port=parsed.port?Number(parsed.port):defaultPort;if(port<1||port>65535)throw new Error("控制端口必须在 1-65535 之间");return{serverAddr:parsed.hostname.replace(/^\[|\]$/g,""),serverPort:port,serverTLS:scheme==="https:"||scheme==="tls:"}};
const remoteAddress=(address:string,port?:number)=>{if(!address||!port)return"—";const host=address.includes(":")&&!address.startsWith("[")?`[${address}]`:address;return`${host}:${port}`};
const proxyTypeLabel=(value:string)=>value==="https"?"HTTP + HTTPS":value.toUpperCase();
function Icon({name}:{name:string}){const d:Record<string,string>={grid:"M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z",route:"M5 7h10a4 4 0 0 1 4 4v6m0 0-3-3m3 3-3 3",chart:"M7 5h13M7 12h13M7 19h13M3 5h.01M3 12h.01M3 19h.01",plus:"M12 5v14M5 12h14",settings:"M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1V21h-4v-.08a1.7 1.7 0 0 0-1.1-1.55 1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1-.4H3v-4h.08A1.7 1.7 0 0 0 4.63 8.5a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1V3h4v.08A1.7 1.7 0 0 0 15.5 4a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.15.38.37.72.6 1 .27.28.62.41 1 .4h.08v4H21c-.4 0-.75.13-1 .4-.25.27-.45.58-.6.92Z",copy:"M8 8h12v12H8zM16 8V4H4v12h4",refresh:"M20 7v5h-5M4 17v-5h5M18 9a7 7 0 0 0-12-2M6 15a7 7 0 0 0 12 2"};return <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={d[name]}/></svg>}
export default function App(){
 const baseUrl=inTauri?"http://127.0.0.1:7101":"";const [stats,setStats]=useState<Stats|null>(null);const [proxies,setProxies]=useState<Proxy[]>([]);const [requests,setRequests]=useState<Request[]>([]);const [error,setError]=useState("");const [modal,setModal]=useState(false);const [deleteTarget,setDeleteTarget]=useState<Proxy|null>(null);const [settings,setSettings]=useState(false);const [section,setSection]=useState<"overview"|"proxies"|"requests"|"settings">("overview");const [busy,setBusy]=useState(false);const [toast,setToast]=useState("");const[lang,setLang]=useState<"zh"|"en">(()=>localStorage.getItem("tunnelx-language")==="en"?"en":"zh");const[theme,setTheme]=useState<"system"|"light"|"dark">(()=>{const saved=localStorage.getItem("tunnelx-theme");return saved==="light"||saved==="dark"?saved:"system"});const tr=(zh:string,en:string)=>lang==="zh"?zh:en;
	const[authed,setAuthed]=useState(false);const[configured,setConfigured]=useState<boolean|null>(null);
 useEffect(()=>{const media=matchMedia("(prefers-color-scheme: dark)");const apply=()=>{document.documentElement.dataset.theme=theme==="system"?(media.matches?"dark":"light"):theme};apply();localStorage.setItem("tunnelx-theme",theme);media.addEventListener("change",apply);return()=>media.removeEventListener("change",apply)},[theme]);useEffect(()=>{const move=(e:PointerEvent)=>{document.documentElement.style.setProperty("--mx",`${e.clientX}px`);document.documentElement.style.setProperty("--my",`${e.clientY}px`)};window.addEventListener("pointermove",move,{passive:true});return()=>window.removeEventListener("pointermove",move)},[]);
	useEffect(()=>{api<{configured:boolean}>(baseUrl,"/api/setup-status").then(r=>setConfigured(r.configured)).catch(e=>setError(String(e)))},[baseUrl]);
 const refresh=useCallback(async()=>{if(!authed)return;try{const [s,p,r]=await Promise.all([api<Stats>(baseUrl,"/api/stats"),api<Proxy[]>(baseUrl,"/api/proxies"),api<Request[]>(baseUrl,"/api/requests")]);setStats(s);setProxies(p||[]);setRequests(r||[]);setError("")}catch{setError("offline");setStats(null)}},[authed,baseUrl]);
 useEffect(()=>{refresh();const id=setInterval(refresh,3000);return()=>clearInterval(id)},[refresh]);
	useEffect(()=>{if(modal){const input=document.querySelector<HTMLInputElement>('input[name="server_addr"]');if(input)input.value=""}},[modal]);
const notify=(v:string)=>{setToast(v);setTimeout(()=>setToast(""),2200)};const go=(next:"overview"|"proxies"|"requests"|"settings")=>{setSection(next);setSettings(next==="settings");if(next!=="settings"&&next!=="overview")setTimeout(()=>document.getElementById(next)?.scrollIntoView({behavior:"smooth",block:"start"}),0)};
	async function signIn(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),password=String(f.get("password")||""),confirm=String(f.get("confirm")||"");try{if(configured===false){if(password!==confirm)throw new Error(tr("两次输入的密码不一致","Passwords do not match"));await api(baseUrl,"/api/setup","POST",{password});setConfigured(true);setError("");return}await api(baseUrl,"/login","POST",{password});setAuthed(true);setError("")}catch(e){setError(String(e))}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const token=String(f.get("token")||"").trim();if(/^https?:\/\//i.test(token)){notify(tr("认证令牌不能填写服务器网址","The authentication token cannot be a server URL"));setBusy(false);return}try{const{serverAddr,serverPort,serverTLS}=endpoint(String(f.get("server_addr")||""));await api(baseUrl,"/api/request-proxy","POST",{server_addr:serverAddr,server_port:serverPort,server_tls:serverTLS,token,local_ip:"127.0.0.1",local_port:Number(f.get("local_port")),proxy_type:f.get("proxy_type")});setModal(false);notify(tr("代理申请已提交","Proxy request submitted"));refresh()}catch(e){notify(`${tr("提交失败","Request failed")}：${String(e).replace(/^Error:\s*/,"")}`)}finally{setBusy(false)}}
 async function deleteProxy(proxy:Proxy){setBusy(true);try{await api(baseUrl,"/api/delete-proxy","POST",{name:proxy.name,server_addr:proxy.server_addr,server_port:proxy.server_port});setDeleteTarget(null);notify(tr("代理已删除；服务端离线时将在下次连接后同步","Proxy deleted; an offline server will be synchronized after reconnecting"));setTimeout(refresh,300)}catch(e){notify(`${tr("删除失败","Delete failed")}：${String(e).replace(/^Error:\s*/,"")}`)}finally{setBusy(false)}}
 const live=useMemo(()=>stats?.active_proxies??proxies.length,[stats,proxies]);
	if(!authed)return <div className="login-page"><div className="ambient-bg" aria-hidden="true"><div className="ambient-dots"/><div className="ambient-glow"/></div><div className="login-brand"><span className="brand-mark"><i/><i/></span><span>Tunnel<span>X</span></span></div><form className="login-card" onSubmit={signIn}><span className="eyebrow">{tr("客户端管理","CLIENT ADMINISTRATION")}</span><h1>{configured===false?tr("设置客户端密码","Set your password."):tr("欢迎回来","Welcome back.")}</h1><p>{configured===false?tr("首次运行，请为客户端创建管理密码。","Create the administration password for this client."):tr("输入客户端管理密码以继续。","Enter the client password to continue.")}</p><label>{tr("密码","Password")}<input name="password" type="password" minLength={8} autoFocus required/></label>{configured===false&&<label>{tr("确认密码","Confirm password")}<input name="confirm" type="password" minLength={8} required/></label>}{error&&<div className="form-error">{error}</div>}<button className="primary-button" disabled={configured===null}>{configured===false?tr("保存密码","Save password"):tr("登录","Sign in")}</button></form></div>;
 return <div className="app-shell"><div className="ambient-bg" aria-hidden="true"><div className="ambient-dots"/><div className="ambient-glow"/></div><aside className="sidebar"><div className="brand"><span className="brand-mark"><i/><i/></span><span>Tunnel<span>X</span></span></div><nav><button className={`nav-item ${section==="overview"?"active":""}`} onClick={()=>go("overview")}><Icon name="grid"/>{tr("概览","Overview")}</button><button className={`nav-item ${section==="proxies"?"active":""}`} onClick={()=>go("proxies")}><Icon name="route"/>{tr("代理","Proxies")}<b>{proxies.length}</b></button><button className={`nav-item ${section==="requests"?"active":""}`} onClick={()=>go("requests")}><Icon name="chart"/>{tr("申请","Requests")}<b>{requests.length}</b></button></nav><div className="sidebar-bottom"><button className={`nav-item ${section==="settings"?"active":""}`} onClick={()=>go("settings")}><Icon name="settings"/>{tr("设置","Settings")}</button><div className="sidebar-endpoint"><span>CLIENT</span><strong>:7101</strong></div></div></aside>
 <main className="workspace"><header className="topbar"><div className="topbar-left"><div className="topbar-brand"><span className="brand-mark"><i/><i/></span><span>Tunnel<span>X</span></span></div><div className="breadcrumb"><span>{tr("客户端","Client")}</span><i>/</i><strong>{section==="settings"?tr("设置","Settings"):section==="proxies"?tr("代理","Proxies"):section==="requests"?tr("申请","Requests"):tr("概览","Overview")}</strong></div></div><div className="top-actions"><div className="client-tabs"><button className={section!=="settings"?"active":""} onClick={()=>go("overview")}><Icon name="grid"/>{tr("概览","Overview")}</button><button className={section==="settings"?"active":""} onClick={()=>go("settings")}><Icon name="settings"/>{tr("设置","Settings")}</button></div><div className="current-endpoint"><span>{tr("本地客户端","LOCAL CLIENT")}</span><strong>:7101</strong></div><div className={`connection-pill ${stats?.connected?"online":""}`}><span/>{stats?tr("运行中","Running"):tr("离线","Offline")}</div></div></header>{settings&&<Settings baseUrl={baseUrl} lang={lang} theme={theme} tr={tr} setLang={v=>{setLang(v);localStorage.setItem("tunnelx-language",v)}} setTheme={setTheme}/>}<section className={`content ${settings?"content-hidden":""}`} id="overview"><div className="title-row"><div><p className="eyebrow">TUNNELX / CLIENT CONTROL</p><h1>{tr("私有路由，尽在掌控","Private routes, under control.")}</h1><p>{error?tr("无法连接本地客户端 Dashboard API","Unable to reach the local Dashboard API"):`${tr("本地管理端口","Local dashboard")} :7101`}</p></div><button className="primary-button" onClick={()=>setModal(true)}><Icon name="plus"/>{tr("申请代理","Request proxy")}</button></div>
 <section className="status-card"><div className="status-copy"><div className="pulse"><span/><i/></div><div><span className="card-label">{tr("客户端运行状态","CLIENT RUNTIME")}</span><h2>{stats?tr("本地客户端运行中","Local client is running"):tr("本地客户端离线","Local client is offline")}</h2><p>{error?tr("等待本地客户端服务启动","Waiting for the local client service"):tr("可向不同地址和端口的服务端申请代理","Ready to request proxies from servers on different addresses and ports")}</p></div></div><div className="status-meta"><div><span>UPTIME</span><strong>{duration(stats?.uptime)}</strong></div><div><span>{tr("管理端口","DASHBOARD")}</span><strong>:7101</strong></div></div></section>
 <section className="metrics-grid"><article><span>{tr("活跃代理","ACTIVE PROXIES")}</span><div><strong>{String(live).padStart(2,"0")}</strong><em>routes</em></div><small><i/>Live configuration</small></article><article><span>{tr("流入流量","TRAFFIC IN")}</span><div><strong>{bytes(stats?.total_bytes_in).split(" ")[0]}</strong><em>{bytes(stats?.total_bytes_in).split(" ")[1]}</em></div><small>Received through tunnels</small></article><article><span>{tr("流出流量","TRAFFIC OUT")}</span><div><strong>{bytes(stats?.total_bytes_out).split(" ")[0]}</strong><em>{bytes(stats?.total_bytes_out).split(" ")[1]}</em></div><small>Sent through tunnels</small></article></section>
 <DataSection id="proxies" title={tr("活跃代理","Active proxies")} subtitle={tr("当前配置的本地端点。","Currently configured local endpoints.")}><div className="data-table proxy-table"><div className="data-head"><span>{tr("名称 / 服务端","NAME / SERVER")}</span><span>{tr("类型","TYPE")}</span><span>{tr("本地端口","LOCAL")}</span><span>{tr("远程地址","REMOTE ADDRESS")}</span><span>{tr("连接数","CONNECTIONS")}</span><span>{tr("流量","TRAFFIC")}</span><span>{tr("操作","ACTION")}</span></div>{proxies.length?proxies.map(p=><div className="data-row" key={`${p.server_addr}:${p.server_port}|${p.name}`}><span><strong>{p.name}</strong><small>{p.server_addr}:{p.server_port}</small></span><span>{proxyTypeLabel(p.type)}</span><code>:{p.local_port}</code><code>{remoteAddress(p.server_addr,p.remote_port)}</code><span>{p.connections}</span><span>↓ {bytes(p.bytes_in)} · ↑ {bytes(p.bytes_out)}</span><button className="delete-proxy" onClick={()=>setDeleteTarget(p)} title={tr("删除并释放端口","Delete and release port")} aria-label={tr("删除代理","Delete proxy")}>×</button></div>):<Empty text={tr("暂无代理配置","No proxies configured")}/>}</div></DataSection>
 <DataSection id="requests" title={tr("代理申请","Proxy requests")} subtitle={tr("来自服务端的审批状态。","Approval state from the server.")}><div className="data-table six"><div className="data-head"><span>{tr("申请","REQUEST")}</span><span>{tr("本地端口","LOCAL")}</span><span>{tr("类型","TYPE")}</span><span>{tr("状态","STATUS")}</span><span>{tr("远程地址","REMOTE ADDRESS")}</span><span>{tr("时间","TIME")}</span></div>{requests.length?requests.map(r=><div className="data-row" key={r.id}><code>{r.id.slice(0,8)}</code><code>:{r.local_port}</code><span>{proxyTypeLabel(r.proxy_type)}</span><span className={`state ${r.status}`}>{r.status}</span><code>{remoteAddress(r.server_addr,r.remote_port)}</code><span>{new Date(r.request_time).toLocaleString()}</span></div>):<Empty text={tr("暂无代理申请","No proxy requests")}/>}</div></DataSection></section></main>
 {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div><span className="eyebrow">{tr("新建路由","NEW ROUTE")}</span><h2>{tr("申请代理","Request a proxy")}</h2><p>{tr("填写完整服务地址。HTTP + HTTPS 模式由服务端终止 TLS，再转发到本地 HTTP 服务。","Enter the complete server URL. HTTP + HTTPS mode terminates TLS on the server and forwards plain HTTP to the local service.")}</p></div><label>{tr("完整服务地址","Complete server URL")}<input name="server_addr" required placeholder="https://xcloudy.cn:7100/" autoComplete="off"/></label><label>{tr("代理类型","Proxy type")}<select name="proxy_type"><option value="https">HTTP + HTTPS</option><option value="tcp">TCP</option><option value="udp">UDP</option></select></label><label>{tr("认证令牌","Authentication token")}<input name="token" type="password" required autoComplete="off"/></label><label>{tr("本地端口","Local port")}<input name="local_port" type="number" min="1" max="65535" placeholder="8080" required/></label><div className="modal-actions"><button type="button" className="ghost-button" onClick={()=>setModal(false)}>{tr("取消","Cancel")}</button><button className="primary-button" disabled={busy}>{busy?tr("提交中…","Submitting…"):tr("提交申请","Submit request")}</button></div></form></div>}{deleteTarget&&<div className="modal-backdrop" onMouseDown={()=>setDeleteTarget(null)}><div className="modal compact" onMouseDown={e=>e.stopPropagation()}><div><span className="eyebrow">{tr("删除代理","DELETE PROXY")}</span><h2>{deleteTarget.name}</h2><p>{tr(`将同时从客户端和 ${remoteAddress(deleteTarget.server_addr,deleteTarget.server_port)} 服务端删除代理，并立即释放公网端口。`,`The proxy will be removed from both the client and ${remoteAddress(deleteTarget.server_addr,deleteTarget.server_port)}, immediately releasing the public port.`)}</p></div><div className="modal-actions"><button type="button" className="ghost-button" onClick={()=>setDeleteTarget(null)}>{tr("取消","Cancel")}</button><button type="button" className="primary-button destructive" disabled={busy} onClick={()=>deleteProxy(deleteTarget)}>{busy?tr("删除中…","Deleting…"):tr("确认删除","Delete")}</button></div></div></div>}{toast&&<div className="toast">{toast}</div>}</div>}
function DataSection({id,title,subtitle,children}:{id?:string;title:string;subtitle:string;children:React.ReactNode}){return <section className="tunnels-section" id={id}><div className="section-heading"><div><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</section>};function Empty({text}:{text:string}){return <div className="empty-state">{text}</div>}
