import {FormEvent,useEffect,useState} from "react";
import {invoke} from "@tauri-apps/api/core";
export type ThemeMode="system"|"light"|"dark";
type Props={baseUrl:string;lang:"zh"|"en";theme:ThemeMode;tr:(zh:string,en:string)=>string;setLang:(value:"zh"|"en")=>void;setTheme:(value:ThemeMode)=>void};
const inTauri="__TAURI_INTERNALS__" in window;
async function call<T>(baseUrl:string,path:string,method="GET",body?:unknown):Promise<T>{if(inTauri)return invoke<T>("api_request",{baseUrl,path,method,body:body??null,form:null});const response=await fetch(path,{method,credentials:"include",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});if(!response.ok)throw new Error(await response.text());return response.json()}
export default function Settings({baseUrl,lang,theme,tr,setLang,setTheme}:Props){
 const[port,setPort]=useState("7101"),[message,setMessage]=useState(""),[passwordMessage,setPasswordMessage]=useState(""),[saving,setSaving]=useState(false);
 const errorText=(error:unknown)=>{const text=String(error).replace(/^Error:\s*/,"");if(text==="Current password is incorrect")return tr("当前密码不正确","Current password is incorrect");return text};
 useEffect(()=>{call<{port:number}>(baseUrl,"/api/runtime-config").then(r=>setPort(String(r.port))).catch(()=>setMessage(tr("无法读取启动端口","Unable to read startup port")))},[baseUrl]);
 async function save(e:FormEvent){e.preventDefault();const value=Number(port);if(!Number.isInteger(value)||value<1||value>65535){setMessage(tr("端口必须在 1 到 65535 之间","Port must be between 1 and 65535"));return}setSaving(true);try{const result=await call<{port:number}>(baseUrl,"/api/runtime-config","POST",{port:value});setPort(String(result.port));setMessage(tr("已保存，重启后生效","Saved. Restart to apply."))}catch(e){setMessage(String(e))}finally{setSaving(false)}}
 async function changePassword(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),current=String(f.get("current_password")||""),next=String(f.get("new_password")||""),confirm=String(f.get("confirm_password")||"");if(next!==confirm){setPasswordMessage(tr("两次新密码不一致","New passwords do not match"));return}try{await call(baseUrl,"/api/password","POST",{current_password:current,new_password:next});form.reset();setPasswordMessage(tr("密码已更新","Password updated"))}catch(e){setPasswordMessage(errorText(e))}}
 return <section className="content settings-content"><div className="settings-page-inner"><header className="settings-head"><span className="eyebrow">PREFERENCES</span><h2>{tr("设置","Settings")}</h2><p>{tr("管理客户端安全、启动方式和界面偏好。","Manage client security, startup and interface preferences.")}</p></header>
 <section className="settings-card"><div><span className="setting-kicker">SECURITY</span><h3>{tr("修改管理密码","Change password")}</h3><p>{tr("需要验证当前密码，新密码至少 8 位。","Verify the current password; the new password must be at least 8 characters.")}</p></div><form className="password-control" onSubmit={changePassword}><input name="current_password" type="password" placeholder={tr("当前密码","Current password")} required/><input name="new_password" type="password" minLength={8} placeholder={tr("新密码","New password")} required/><input name="confirm_password" type="password" minLength={8} placeholder={tr("确认新密码","Confirm new password")} required/><button>{tr("修改密码","Change password")}</button>{passwordMessage&&<small>{passwordMessage}</small>}</form></section>
 <section className="settings-card"><div><span className="setting-kicker">STARTUP</span><h3>{tr("启动端口","Startup port")}</h3><p>{tr("修改后写入配置文件，下次重启客户端时生效。","Saved to configuration and applied after the next restart.")}</p></div><form className="port-control" onSubmit={save}><input value={port} onChange={e=>setPort(e.target.value.replace(/\D/g,""))}/><button disabled={saving}>{saving?"…":tr("保存","Save")}</button>{message&&<small>{message}</small>}</form></section>
 <section className="settings-card"><div><span className="setting-kicker">LANGUAGE</span><h3>{tr("界面语言","Interface language")}</h3><p>{tr("选择导航、状态和操作的显示语言。","Choose the language for navigation, status and actions.")}</p></div><div className="option-buttons"><button className={lang==="zh"?"active":""} onClick={()=>setLang("zh")}>中文</button><button className={lang==="en"?"active":""} onClick={()=>setLang("en")}>English</button></div></section>
 <section className="settings-card"><div><span className="setting-kicker">APPEARANCE</span><h3>{tr("外观","Appearance")}</h3><p>{tr("选择跟随系统、浅色或深色主题。","Follow the system theme, or choose light or dark.")}</p></div><div className="theme-options"><button className={theme==="system"?"active":""} onClick={()=>setTheme("system")}><span className="theme-preview system"/><span>{tr("跟随系统","System")}</span></button><button className={theme==="light"?"active":""} onClick={()=>setTheme("light")}><span className="theme-preview light"/><span>{tr("浅色","Light")}</span></button><button className={theme==="dark"?"active":""} onClick={()=>setTheme("dark")}><span className="theme-preview dark"/><span>{tr("深色","Dark")}</span></button></div></section>
 <section className="about-card"><div className="about-mark"><img src="/tunnelx.svg" alt="TunnelX"/></div><div className="about-copy"><span className="setting-kicker">ABOUT</span><h2>TunnelX Client</h2><p>{tr("轻量、现代的内网穿透客户端。","A lightweight, modern tunneling client.")}</p><div className="thanks"><span>{tr("特别致谢","With thanks to")}</span><strong>Go</strong><strong>React</strong><strong>Tauri</strong><strong>Vite</strong><strong>XCloudy</strong></div></div><span className="version">v1.0.0</span></section>
 </div></section>}
